disabled_rules:
  - multiple_closures_with_trailing_closure
  - orphaned_doc_comment
  - force_cast
  - force_try
excluded:
  - Packages/*/Package.swift
  - Packages/*/Tests
  - Tests
  - Shared/Models/CoreData/*swift
identifier_name:
  min_length:
    warning: 2
  allowed_symbols: "_"
